Trender/Trender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls'),name='account_app'),
    path('userpage/',include('userpage.urls'),name='userpage'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Trender/userpage/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import Search_User

app_name = 'userpage'

urlpatterns = [
    path('',views.userHome,name='userHome'),
    path('post', views.post, name='post'),
    path('like_dislike', views.likePost, name='like_dislike_post'),
    path("<int:postId>", views.delPost, name='delPost'),
    path("<str:username>", views.userProfile, name='userProfile' ),
    path("user/follow/<str:username>", views.follow, name="follow"),
    path("search/", Search_User.as_view(), name="search_user"),
]

Trender/userpage/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    captions = models.CharField(max_length=200)
    image = models.ImageField(upload_to = "user_image")
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + ' '+ str(self.date.date())


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    userImage = models.ImageField(upload_to = "Profiles", default = "default/default.png")
    bio = models.CharField(max_length=100, blank = True)
    connection = models.CharField(max_length = 100, blank=True)
    follower = models.IntegerField(default=0)
    following = models.IntegerField(default=0)


    def __str__(self):
        return str(self.user)

class Like(models.Model):
    user = models.ManyToManyField(User, related_name="linkingUser")
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    
    @classmethod
    def like(cls, post, liking_user):
        obj, create  = cls.objects.get_or_create(post = post)
        obj.user.add(liking_user)

    @classmethod
    def dislike(cls, post, disliking_user):
        obj, create  = cls.objects.get_or_create(post = post)
        obj.user.remove(disliking_user)

    def __str__(self):
        return str(self.post)
class Following(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    followed= models.ManyToManyField(User, related_name="followed")
    follower = models.ManyToManyField(User, related_name="follower")
    @classmethod
    def follow(cls, user, another_account):
        obj, create = cls.objects.get_or_create(user= user)
        obj.followed.add(another_account)

    
    @classmethod
    def unfollow(cls, user, another_account):
        obj, create = cls.objects.get_or_create(user= user)
        obj.followed.remove(another_account)

    def __str__(self):
        return str(self.user)

Trender/userpage/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib import messages
from .models import Post, Profile, Like, Following
from django.contrib.auth.models import User
# Create your views here.
import os, json
from django.views.generic import ListView
from django.core.paginator import Paginator
from django.conf import settings
def userHome(request):
    user = Following.objects.get(user = request.user)
    following_obj = Following.objects.get(user = request.user)
    followed_users = [i for i in user.followed.all()]
    followed_users.append(request.user)
    posts = Post.objects.filter(user__in = followed_users).order_by('-pk')
    liked_ = [i for i in posts if Like.objects.filter(post = i, user = request.user)]
    data = {'posts':posts,
    'liked_post':liked_}
    return render(request,"userpage/postfeed.html",data)

def post(request):
    if request.method=="POST":
        image_= request.FILES['image']
        captions_ =request.POST.get('captions','')
        user_ = request.user
        post_obj = Post(user=user_, captions=captions_, image=image_)
        post_obj.save()
        messages.success(request, "Sucessfully Posted")
        return redirect('/userpage')
    else:
        messages.error(request,"Something went Wrong : (")
        return redirect('/userpage')

def userProfile(request, username):
    user = User.objects.filter(username=username)
    if user:
        user = user[0]
        profile = Profile.objects.get(user=user)
        post = getPosts(user)
        bio = profile.bio
        conn = profile.connection
        user_img = profile.userImage
        is_following = Following.objects.filter(user = request.user, followed = user)
        
        following_obj = Following.objects.get(user = user)
        follower, following = following_obj.follower.count(), following_obj.followed.count()
        data = {
            'user_obj':user,
            'bio':bio,
            'conn':conn,
            'follower':follower,
            'following': following,
            'userImg':user_img,
            'posts':post,
            'connection':is_following
        }
    else: return HttpResponse("NO SUCH USER")

    return render(request, 'userpage/userProfile.html', data)

def getPosts(user):
    post_obj = Post.objects.filter(user=user)
    img_List = [post_obj[i:i+3] for i in range(0,len(post_obj),3)]
    return img_List

def delPost(request, postId):
    post_ = Post.objects.filter(pk=postId)
    # print(post_)
    # print(post_[0].image.url, post_[0].image.path)
    image_path = post_[0].image.url
    os.remove(post_[0].image.path)
    post_.delete()
    messages.info(request, "Post Deleted")
    return redirect('/userpage')

def likePost(request):
    post_id = request.GET.get("likeId", "")
    post = Post.objects.get(pk=post_id)
    user = request.user
    like = Like.objects.filter(post = post, user=user)
    liked = False

    if like:
        Like.dislike(post, user)
    else:
        liked = True
        Like.like(post, user)

    resp = {
        'liked':liked
    }
    response = json.dumps(resp)
    return HttpResponse(response, content_type = "application/json")

def follow(request, username):
    main_user = request.user
    to_follow = User.objects.get(username= username)

    following = Following.objects.filter(user = main_user, followed= to_follow)
    is_following = True if following else False

    if is_following:
        Following.unfollow(main_user, to_follow)
        is_following =False
    else:
        Following.follow(main_user, to_follow)
        is_following = True

    resp = {
        "following" : is_following,
    }
    response = json.dumps(resp)
    return HttpResponse(response, content_type="application/json")

class Search_User(ListView):
    model = User
    template_name = "userpage/searchUser.html"
    paginate_by = 2
    def get_queryset(self):
        username = self.request.GET.get("username","")
        print(username)
        queryset = User.objects.filter(username__icontains=username)
        print(queryset)
        return queryset

Trender/templates/userpage/postfeed.html
{% extends 'base.html' %}
{% load static %}

{% block nav_btn1 %}
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-primary ml-4" data-toggle="modal" data-target="#PostModal">
Post
</button>
<a class="btn btn-outline-primary ml-4" href="/logout">
Logout
</a>
{% endblock nav_btn1 %}

{% block css %}

#post_img
{
  width:450;
  height:360;
}
.post_div
{
  width:600px;
}
{% endblock css%}

{% block body %}
{% for i in posts %}
<div class="container my-4 post_div" id="{{i.id}}">
<div class="card">
    <h5 class="card-header"><a href="{% url 'userpage:userProfile' i.user %}">{{i.user}}</a><small>{{i.data.date}}</small></h5>
    <div class="card-body">
      <p class="card-text">{{i.captions}}</p>
      {% if i.image %}
      <img src="{{i.image.url}}" alt="Image" id='post_img'>
      {% endif %}
      <hr size='30px'>

      <button class="btn btn-light mr-3 like" id="{{ i.id }}">
        {% if i in liked_post %}
            <a href="{% url 'userpage:like_dislike_post' %}" style="color:red;" id="likebtn{{ i.id }}"> Liked </a>
        {% else %}
            <a href="{% url 'userpage:like_dislike_post' %}" style="color:red;" id="likebtn{{ i.id }}"> Like </a>
        {% endif %}
      </button>


      {% if request.user == i.user %}
      <a class="btn btn-primary mr-4 delete" href="{% url 'userpage:delPost' i.id%}" id="{{ i.id }}">Delete Post</a>
      {% endif %}
    </div>
  </div>
</div>
{% endfor %}
{% endblock body %}

{% block modals %}


<!-- Modal -->
<div class="modal fade" id="PostModal" tabindex="-1" aria-labelledby="PostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="PostModalLabel">Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/userpage/post" method="POST", enctype="multipart/form-data"> 
          {% csrf_token %}
          <label for="image">Image:</label>
          <input type="file" name="image" id="image">
          <br><br>
          <label for="capttext">Captions:</label>
          <br>
          <textarea name="captions" id="captions" cols="30" rows="10" placeholder="Any Captions......" class="ml-4"></textarea>
         <hr size='30'> 
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Post IT</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% block js %}
<script>
  $(".delete").click(function (e) {
    var id = this.id;
    var href = this.href;
    //console.log(href, id) // get href from link 
    e.preventDefault(); // don't follow the link

    $.ajax({
      url: href,
      data: {},
    });

    $("#" + id).fadeOut(1000);

  });

  
  $(".like").click(function (e) {
    var id = this.id; //$(this).attr('id');
    var href = $('.like').find('a').attr('href');
    e.preventDefault(); // don't follow the link

    $.ajax({
        url: href,
        data: {
          'likeId': id
        },
        success: function(response){
          if(response.liked){
            $('#likebtn' + id).html("Liked");
          }
          else{
            $('#likebtn' + id).html("Like");
          }
        }
      })
  });


</script>
{% endblock js %}
{% endblock modals %}

Trender/templates/userpage/searchUser.html
{% extends 'base.html' %}

{% block body %}
  <div class="container my-4 mx-4">
    {% for i in object_list %}
    
    <div class="card my-2">
      <div class="card-body">
        <a href="{% url 'userpage:userProfile' i.username %}">{{i.username}}</a>
      </div>
    </div>
    {% endfor %}

    {% if is_paginated %}
      <!-- <a href="?page=1" role="button" class="btn btn-outline-primary">1</a> -->

      {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}" role="button" class="btn btn-outline-primary">prev</a>
      {% endif %}

      {% if page_obj.number != 1 %}
      <a href="?page={{ page_obj.number }}" class="btn btn-primary">{{ page_obj.number }}</a>
      {% endif %}

      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" role="button" class="btn btn-outline-primary">next</a>
      {% endif %}

    {% endif %}

  </div>
{% endblock body %}

Trender/templates/userpage/userProfile.html
{% extends 'base.html' %}


{% block css %}

.userImage
{
width:200px;
height:200px;
border-radius:50%;
}

.info
{
padding-top:2%;
padding-left:3%;
}

.postappro{
    width:350px;
    height:200px;
    margin-bottom:15px;
}

hr
{
border-top: 2px solid #000000;
}
#follow
{
    color:blue;
}
#follow:hover
{
    color:white;
}
{% endblock css %}


{% block body %}

<div class="container my-4">
    <div class="media">
        <img src="{{userImg.url}}" class="align-self-start mr-3 userImage" alt="...">
        <div class="media-body info">
            <h4 class="mt-0">{{user_obj.username}}
                {% if connection and not request.user == user_obj %}
                <a type="button" class="btn btn-outline-primary" id="follow" role="button" href="{% url 'userpage:follow' user_obj.username %}" >Unfollow</a>
                {% elif not connection and not request.user == user_obj %}
                <a type="button" class="btn btn-outline-primary" id="follow" role="button" href="{% url 'userpage:follow' user_obj.username %}" >follow</a>
                {% endif %}
            </h4>
            <p>Follower : {{follower}} Following : {{following}}</p>
            <p><b>{{bio}}</b></p>
        </div>
    </div>

    <hr>

    <div class = "row">
        {% for i in posts %}
            {% for j in i %}
            <div class = "col-md-4">
                <img src="{{j.image.url}}" alt="Image" class='postappro'>
            </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock body %}

{% block js%}
<script type="text/javascript">
    $("#follow").click(function(e){
        e.preventDefault();
        var href =  this.href;
        $.ajax({
            url : href,
            success : function(response){
                if(response["following"]){
                    $("#follow").html("Unfollow");
                }
                else{
                    $("#follow").html("Follow");
                }
            }
        })
    })
</script>
{% endblock js%}